---
default_iu3:
  train2:
      data_path: 'IU/*_split/*.wav'
  convert:
      one_full_wav: False
      batch_size: 4
---
iu:
  train2:
      data_path: 'IU/*_split/*.wav'
      batch_size: 64
  convert:
      one_full_wav: False
      batch_size: 4