---
default:
  test1:
    batch_size: 128
  train2:
#    lr: 0.0001
    steps_per_epoch: 1
---
mix_1:
  train2:
    num_mixtures: 1
---
mix_2:
  train2:
    num_mixtures: 2
---
mix_10:
  train2:
    num_mixtures: 10
---
mix_5_256:
  train2:
    hidden_units: 256
    num_mixtures: 10
---
mol_iu:
  train2:
    data_path: '/data/private/vc/datasets/IU/*_split/*.wav'
    clip_value_max: 3.
    clip_value_min: -3.
    clip_norm: 50
    dropout_rate: 0.1
    lr_cyclic_margin: 0.
  test2:
    data_path: '/data/private/vc/datasets/IU/*_split/*.wav'
  convert:
    data_path: '/data/private/vc/datasets/test/2018.wav'
    one_full_wav: True
    batch_size: 3
    emphasis_magnitude: 1.3
---
mol_1_iu:
  train2:
    data_path: '/data/private/vc/datasets/IU/*_split/*.wav'
    clip_value_max: 3.
    clip_value_min: -3.
    clip_norm: 50
    dropout_rate: 0.1
    lr_cyclic_margin: 0.
    n_mixtures: 1
  test2:
    data_path: '/data/private/vc/datasets/IU/*_split/*.wav'
  convert:
    data_path: '/data/private/vc/datasets/test/2018.wav'
    one_full_wav: True
    batch_size: 3
    emphasis_magnitude: 1.3
---
mol_log_iu:
  train2:
    data_path: '/data/private/vc/datasets/IU/*_split/*.wav'
    clip_value_max: 3.
    clip_value_min: -3.
    clip_norm: 50
    dropout_rate: 0.1
    lr_cyclic_margin: 0.
    lr: 0.0001
  test2:
    data_path: '/data/private/vc/datasets/IU/*_split/*.wav'
  convert:
    data_path: '/data/private/vc/datasets/test/2018.wav'
    one_full_wav: True
    batch_size: 3
    emphasis_magnitude: 1.3