---
logdir_path: '/Users/avin/git/vc'

train1:
    data_path: '/Users/avin/git/vc/datasets/timit/TIMIT/TRAIN/*/*/*.wav'
---
train2:
    data_path: '/Users/avin/git/vc/datasets/arctic/slt/*.wav'
    num_gpu: 1
---
test1:
    data_path: '/Users/avin/git/vc/datasets/timit/TIMIT/TEST/*/*/*.wav'
---
test2:
    data_path: '/Users/avin/git/vc/datasets/arctic/slt/*.wav'
---
convert:
    # path
    data_path: '/Users/avin/git/vc/datasets/arctic/bdl/*.wav'